# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QWidget, QMainWindow

from forms.game_form import Ui_Form
from forms.settings_window import SettingsWindow


class MainWindow(QMainWindow):
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(500, 400)
        self.setStyleSheet("background-color: rgb(255, 246, 192);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 170, 200, 45))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setFlat(True)
        self.pushButton.setStyleSheet("border:none; background-color: none;")
        self.pushButton.clicked.connect(self.start_game)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start_game)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 225, 200, 45))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setStyleSheet("border:none; background-color: none;")
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.show_rules)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 280, 200, 45))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setStyleSheet("border:none; background-color: none;")
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.clicked.connect(self.show_settings_window)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 335, 200, 45))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setStyleSheet("border:none; background-color: none;")
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(QApplication.quit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(125, 60, 250, 90))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.setCentralWidget(self.centralwidget)
        self.rules_window = QMessageBox()
        self.rules_window.setWindowTitle("Правила игры")
        self.rules_window.setText("Вы должны загнать шар в ворота  того же цвета.")
        font.setPointSize(12)
        self.rules_window.setFont(font)
        self.rules_window.setIcon(QMessageBox.Information)
        self.rules_window.setStandardButtons(QMessageBox.Ok)
        self.rules_window.button(QMessageBox.Ok).setFont(font)
        self.rules_window.button(QMessageBox.Ok).setFlat(True)
        self.rules_window.button(QMessageBox.Ok).setStyleSheet("border:none; background-color: none;")
        self.rules_window.button(QMessageBox.Ok).setFocusPolicy(QtCore.Qt.NoFocus)
        self.rules_window.setStyleSheet("background-color: rgb(255, 246, 192);")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def start_game(self):
        self.game_window = QWidget()
        self.game_ui = Ui_Form()
        self.game_ui.setupUi(self.game_window)

        self.close()
        self.game_window.show()

    def show_rules(self):
        self.rules_window.exec_()

    def show_settings_window(self):
        settings_window = SettingsWindow(parent=self)
        settings_window.exec_()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Кугейм"))
        self.pushButton.setText(_translate("MainWindow", "Начать игру"))
        self.pushButton_2.setText(_translate("MainWindow", "Правила"))
        self.pushButton_3.setText(_translate("MainWindow", "Настройки"))
        self.pushButton_4.setText(_translate("MainWindow", "Выйти"))
        self.label.setText(_translate("MainWindow", "Кугейм"))

